# https://typst.app/blog/2023/package-manager/
# https://github.com/typst/packages
[package]
name = "lipsum"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "src/lib.typ"

authors = ["ziv3@outlook.com"]

repository = "https://github.com/icyzeroice/typst-packages/tree/main/packages/lipsum"
license = "MIT"
